suppressMessages(library(RobStatTM))
data(mineral)
set.seed(1); f1 <- lmrobdetMM(zinc ~ copper, data=mineral)
d1 <- drop1(f1)
cat("--- mineral single-term ---\n"); print(d1)
cat("class:", class(d1), "\n"); cat("colnames:", paste(colnames(d1), collapse="|"), "\n")
cat("rownames:", paste(rownames(d1), collapse="|"), "\n")
cat("Df:", paste(d1$Df, collapse="|"), "\n")
cat("RFPE:", paste(format(d1$RFPE, digits=10), collapse="|"), "\n")

data(stackloss)
set.seed(2); f2 <- lmrobdetMM(stack.loss ~ ., data=stackloss)
cat("\n--- stackloss all terms ---\n"); print(drop1(f2))
set.seed(2); f2b <- lmrobdetMM(stack.loss ~ ., data=stackloss)
cat("\n--- stackloss scoped (Air.Flow) ---\n"); print(drop1(f2b, c("Air.Flow")))
