library(RobStatTM)
data(mineral)
fit <- lmrobdetMM(zinc ~ copper, data = mineral)

cat("===== summary() structure =====\n")
s <- summary(fit)
cat("class:\n"); print(class(s))
cat("names:\n"); print(names(s))
cat("str:\n"); str(s, max.level=1)
cat("\n--- summary$coefficients matrix ---\n")
print(s$coefficients)
cat("\n--- summary print output ---\n")
print(s)

cat("\n===== predict() — type='response' default =====\n")
p_default <- predict(fit)
cat("length:", length(p_default), "head:\n"); print(head(p_default))

cat("\n===== predict() with se.fit=TRUE =====\n")
p_se <- predict(fit, se.fit=TRUE)
cat("class:\n"); print(class(p_se))
cat("names:\n"); print(names(p_se))
str(p_se, max.level=1)

cat("\n===== predict() with newdata =====\n")
nd <- data.frame(copper=c(10, 20, 30))
p_new <- predict(fit, newdata=nd)
print(p_new)

cat("\n===== hatvalues() =====\n")
h <- hatvalues(fit)
cat("length:", length(h), "class:", class(h), "head:\n"); print(head(h))

cat("\n===== formals =====\n")
cat("predict.lmrobdetMM formals:\n")
print(formals(RobStatTM:::predict.lmrob))
cat("summary.lmrobdetMM formals:\n")
print(formals(RobStatTM:::summary.lmrobdetMM))
cat("hatvalues.lmrob formals:\n")
print(formals(RobStatTM:::hatvalues.lmrob))
