library(RobStatTM)
data(mineral)

fit_m <- lmrobM(zinc ~ copper, data = mineral)
cat("class(fit_m):\n"); print(class(fit_m))
cat("\npredict?\n")
result <- tryCatch(predict(fit_m), error = function(e) conditionMessage(e))
print(result)
cat("\nhatvalues?\n")
result2 <- tryCatch(hatvalues(fit_m), error = function(e) conditionMessage(e))
print(head(result2))

cat("\n\nfit_dcml summary names:\n")
fit_dcml <- lmrobdetDCML(zinc ~ copper, data = mineral)
print(names(summary(fit_dcml)))
cat("\nfit_dcml summary r.squared present?\n")
s <- summary(fit_dcml)
cat("'r.squared' %in% names(s):", "r.squared" %in% names(s), "\n")
cat("\nfit_lmrobM summary names:\n")
print(names(summary(fit_m)))
