suppressMessages(library(RobStatTM))
cat("=== body(bisquare) ===\n"); print(body(bisquare))
cat("\n=== body(mopt) ===\n");   print(body(mopt))
cat("\n=== bisquare() ===\n");   print(bisquare())
cat("\n=== mopt() ===\n");       print(mopt())
cat("\n=== lmrobdet.control(family='bisquare')$tuning.chi ===\n")
print(lmrobdet.control(family="bisquare")$tuning.chi)
print(lmrobdet.control(family="bisquare")$tuning.psi)
cat("\n=== rho with cc from lmrobdet.control ===\n")
ctrl <- lmrobdet.control(family="bisquare")
u <- c(-2, -1, -0.5, 0, 0.5, 1, 2)
cat("rho:     ", rho(u, family="bisquare", cc=ctrl$tuning.psi), "\n")
cat("rhoprime:", rhoprime(u, family="bisquare", cc=ctrl$tuning.psi), "\n")
cat("rhoprime2:", rhoprime2(u, family="bisquare", cc=ctrl$tuning.psi), "\n")
