library(RobStatTM)
set.seed(42)
data(wine)
X <- as.matrix(wine[, sapply(wine, is.numeric)])

cat("===== summary methods exposed in RobStatTM =====\n")
print(methods("summary", "package:RobStatTM"))
print(methods(class="covRob"))
print(methods(class="covClassic"))
print(methods(class="prcompRob"))
print(methods(class="pcaRobS"))

cat("\n===== covRobMM and summary structure =====\n")
fitMM <- covRob(X, type="MM")
cat("class(fitMM):\n"); print(class(fitMM))
cat("names(fitMM):\n"); print(names(fitMM))
s <- summary(fitMM)
cat("class(summary(fitMM)):\n"); print(class(s))
cat("names(summary(fitMM)):\n"); print(names(s))
cat("str(summary(fitMM)):\n")
str(s, max.level=1)

cat("\n===== covClassic summary =====\n")
fitC <- covClassic(X)
cat("class(fitC):\n"); print(class(fitC))
cat("names(fitC):\n"); print(names(fitC))
sC <- summary(fitC)
cat("class(summary(fitC)):\n"); print(class(sC))
cat("names(summary(fitC)):\n"); print(names(sC))

cat("\n===== prcompRob summary =====\n")
set.seed(42)
pR <- prcompRob(X)
cat("class(pR):\n"); print(class(pR))
cat("names(pR):\n"); print(names(pR))
sP <- summary(pR)
cat("class(summary(pR)):\n"); print(class(sP))
cat("names(summary(pR)):\n"); print(names(sP))
cat("summary(pR) preview:\n"); print(sP)

cat("\n===== pcaRobS summary =====\n")
set.seed(42)
ps <- pcaRobS(X, ncomp=3)
cat("class(ps):\n"); print(class(ps))
cat("names(ps):\n"); print(names(ps))
sps <- try(summary(ps), silent=TRUE)
if (inherits(sps, "try-error")) {
  cat("summary(pcaRobS): NOT AVAILABLE\n"); print(attr(sps, "condition"))
} else {
  cat("class(summary(ps)):\n"); print(class(sps))
  cat("names(summary(ps)):\n"); print(names(sps))
}
