"""Rd → JSON extractor.

Pilot implementation of M1 from ``docs/documentation_plan.md``.

The full M1 spec calls for an R-side extractor using ``tools::Rd_db``,
which gives the most faithful parse tree.  This pilot is a *Python*
implementation that parses the Rd source files directly via regex.
It is sufficient for the RobStatTM corpus because every Rd in this
package was generated by roxygen2 and therefore has a very regular
structure.  The output JSON schema is identical to what the R-based
extractor will produce, so the renderer (``render_rd.py``) does not
need to know which extractor wrote the file.

Usage
-----
    python docs/scripts/extract_rd.py --name lmrobdetMM
    python docs/scripts/extract_rd.py --all

Output
------
One JSON file per Rd at ``docs/_rd_json/<RName>.json`` with fields::

    name          str
    title         str
    description   str
    usage         str            (verbatim R code)
    arguments     [ {r_name, description} ]
    value         [ {r_name, description} ]
    details       str
    sections      { name: body }
    examples_r    str            (verbatim R code)
    seealso       [ str ]        (R names referenced via \\link)
    references    str
    keywords      [ str ]
    author        str
"""
from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass, field, asdict
from pathlib import Path

import os

ROOT = Path(__file__).resolve().parents[2]  # the robstatm-py package folder
OUT_DIR = ROOT / "docs" / "_rd_json"

# The upstream RobStatTM R sources (man/*.Rd) are *legacy context* and live at
# the outer repo root, not inside the package folder. Resolve them via an env
# override first, then the conventional sibling location next to the package.
_MAN_ENV = os.environ.get("ROBSTATM_MAN_DIR")
if _MAN_ENV:
    MAN_DIR = Path(_MAN_ENV)
else:
    MAN_DIR = ROOT.parent / "robstattm" / "RobStatTM-master" / "man"


# ---------------------------------------------------------------- helpers

_BRACE_RE = re.compile(r"\\([A-Za-z]+)\{")


def _read_balanced(text: str, start: int) -> tuple[str, int]:
    """Given text and an index pointing at ``{``, return ``(inside, end)``
    where ``end`` is the index just past the matching ``}``."""
    assert text[start] == "{"
    depth = 0
    i = start
    while i < len(text):
        c = text[i]
        if c == "\\" and i + 1 < len(text):
            i += 2
            continue
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[start + 1 : i], i + 1
        i += 1
    raise ValueError(f"unbalanced braces starting at {start}")


def _find_macro(text: str, name: str) -> tuple[str, int, int] | None:
    """Find first ``\\name{...}`` and return ``(inside, start, end)``."""
    pat = re.compile(r"\\" + re.escape(name) + r"\{")
    m = pat.search(text)
    if m is None:
        return None
    inside, end = _read_balanced(text, m.end() - 1)
    return inside, m.start(), end


def _find_all_macros(text: str, name: str) -> list[tuple[str, int, int]]:
    out = []
    pat = re.compile(r"\\" + re.escape(name) + r"\{")
    pos = 0
    while True:
        m = pat.search(text, pos)
        if m is None:
            break
        inside, end = _read_balanced(text, m.end() - 1)
        out.append((inside, m.start(), end))
        pos = end
    return out


# ---------------------------------------------------------------- conversion

_INLINE_PATTERNS = [
    # \code{X}, \verb{X} → backticked
    (re.compile(r"\\code\{([^{}]*)\}"), r"`\1`"),
    (re.compile(r"\\verb\{([^{}]*)\}"), r"`\1`"),
    # \emph{X} → *X*
    (re.compile(r"\\emph\{([^{}]*)\}"), r"*\1*"),
    # \bold{X}, \strong{X} → **X**
    (re.compile(r"\\bold\{([^{}]*)\}"), r"**\1**"),
    (re.compile(r"\\strong\{([^{}]*)\}"), r"**\1**"),
    # \pkg{X} → **X**
    (re.compile(r"\\pkg\{([^{}]*)\}"), r"**\1**"),
    # \link[base]{foo} → `foo`
    (re.compile(r"\\link\[[^\]]*\]\{([^{}]*)\}"), r"`\1`"),
    # \link{foo} → `foo`  (the renderer will optionally turn this into
    # a cross-reference, but for now we keep the literal R name)
    (re.compile(r"\\link\{([^{}]*)\}"), r"`\1`"),
    # \url{X} → <X>
    (re.compile(r"\\url\{([^{}]*)\}"), r"<\1>"),
    # \email{X} → <X>
    (re.compile(r"\\email\{([^{}]*)\}"), r"<\1>"),
    # \eqn{X}{Y} or \eqn{X} → $X$
    (re.compile(r"\\eqn\{([^{}]*)\}\{[^{}]*\}"), r"$\1$"),
    (re.compile(r"\\eqn\{([^{}]*)\}"), r"$\1$"),
    (re.compile(r"\\deqn\{([^{}]*)\}\{[^{}]*\}"), r"$$\1$$"),
    (re.compile(r"\\deqn\{([^{}]*)\}"), r"$$\1$$"),
    # Stray escapes
    (re.compile(r"\\R\b"), r"R"),
    (re.compile(r"\\dots\b"), r"..."),
]


def _to_text(rd_fragment: str) -> str:
    """Convert a parsed Rd fragment (inside braces) to plain Markdown text."""
    s = rd_fragment
    # Inline patterns only match non-nested braces, so iterate to a fixed
    # point to handle constructs like ``\code{\link[base]{options}}``.
    for _ in range(5):
        prev = s
        for pat, repl in _INLINE_PATTERNS:
            s = pat.sub(repl, s)
        if s == prev:
            break
    # Drop leftover backslash-comments
    s = re.sub(r"^%.*$", "", s, flags=re.MULTILINE)
    # Collapse 3+ blank lines to 2
    s = re.sub(r"\n{3,}", "\n\n", s)
    return s.strip()


# ---------------------------------------------------------------- argument list

def _split_items(block: str) -> list[tuple[str, str]]:
    """Split a ``\\arguments{...}`` or ``\\value{...}`` body into
    ``(name, description)`` pairs."""
    items: list[tuple[str, str]] = []
    pos = 0
    while True:
        m = re.search(r"\\item\{", block[pos:])
        if m is None:
            break
        start = pos + m.start()
        name_inside, name_end = _read_balanced(block, start + len("\\item"))
        # next brace is the description
        # skip whitespace
        i = name_end
        while i < len(block) and block[i].isspace():
            i += 1
        if i >= len(block) or block[i] != "{":
            pos = name_end
            continue
        desc_inside, desc_end = _read_balanced(block, i)
        items.append((name_inside.strip(), _to_text(desc_inside)))
        pos = desc_end
    return items


# ---------------------------------------------------------------- main parse

@dataclass
class RdRecord:
    name: str = ""
    aliases: list[str] = field(default_factory=list)
    title: str = ""
    description: str = ""
    usage: str = ""
    arguments: list[dict] = field(default_factory=list)
    value: list[dict] = field(default_factory=list)
    details: str = ""
    sections: dict[str, str] = field(default_factory=dict)
    examples_r: str = ""
    seealso: list[str] = field(default_factory=list)
    references: str = ""
    keywords: list[str] = field(default_factory=list)
    author: str = ""


def parse_rd(path: Path) -> RdRecord:
    text = path.read_text(encoding="utf-8")
    rec = RdRecord()

    if (m := _find_macro(text, "name")):
        rec.name = m[0].strip()
    rec.aliases = [
        inside.strip() for inside, _, _ in _find_all_macros(text, "alias")
    ]
    if (m := _find_macro(text, "title")):
        rec.title = _to_text(m[0])
    if (m := _find_macro(text, "description")):
        rec.description = _to_text(m[0])
    if (m := _find_macro(text, "usage")):
        rec.usage = m[0].strip()
    if (m := _find_macro(text, "arguments")):
        rec.arguments = [
            {"r_name": n, "description": d} for n, d in _split_items(m[0])
        ]
    if (m := _find_macro(text, "value")):
        rec.value = [
            {"r_name": n, "description": d} for n, d in _split_items(m[0])
        ]
    if (m := _find_macro(text, "details")):
        rec.details = _to_text(m[0])
    if (m := _find_macro(text, "references")):
        rec.references = _to_text(m[0])
    if (m := _find_macro(text, "author")):
        rec.author = _to_text(m[0])
    if (m := _find_macro(text, "examples")):
        rec.examples_r = m[0].strip()

    # \section{Name}{Body}
    pos = 0
    while True:
        m = re.search(r"\\section\{", text[pos:])
        if m is None:
            break
        start = pos + m.start()
        name_inside, name_end = _read_balanced(text, start + len("\\section"))
        i = name_end
        while i < len(text) and text[i].isspace():
            i += 1
        if i >= len(text) or text[i] != "{":
            pos = name_end
            continue
        body_inside, body_end = _read_balanced(text, i)
        rec.sections[name_inside.strip()] = _to_text(body_inside)
        pos = body_end

    # \seealso{...} — pull every \link{...} reference
    if (m := _find_macro(text, "seealso")):
        rec.seealso = [
            inside for inside, _, _ in _find_all_macros(m[0], "link")
        ]

    # \keyword{...} — flat occurrences
    rec.keywords = [
        inside for inside, _, _ in _find_all_macros(text, "keyword")
    ]

    return rec


# ---------------------------------------------------------------- driver

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", help="single Rd to extract (without .Rd)")
    ap.add_argument("--all", action="store_true", help="extract every Rd")
    args = ap.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    if args.name:
        targets = [MAN_DIR / f"{args.name}.Rd"]
    elif args.all:
        targets = sorted(MAN_DIR.glob("*.Rd"))
    else:
        ap.error("pass --name <RName> or --all")
        return

    written = 0
    for rd in targets:
        if not rd.exists():
            print(f"[MISS] {rd.name}")
            continue
        rec = parse_rd(rd)
        out = OUT_DIR / f"{rec.name or rd.stem}.json"
        out.write_text(json.dumps(asdict(rec), indent=2), encoding="utf-8")
        written += 1
        print(f"[OK]   {rd.name:<35s} -> {out.relative_to(ROOT)}")

    print(f"\nwrote {written} JSON file(s) to {OUT_DIR.relative_to(ROOT)}/")


if __name__ == "__main__":
    main()
