"""Sphinx configuration for the RobStatTM-Py documentation site.

The site is built from the hand-curated Markdown pages in this folder
(``api/wrappers/*.md`` are generated by ``scripts/render_rd.py``). It does
NOT import ``robstattm_py`` at build time, so the docs build without R/rpy2
installed, handy for CI and Read the Docs.

Build locally::

    cd robstattm-py
    python -m sphinx -b html docs docs/_build/html
"""
from __future__ import annotations

# -- Project information -----------------------------------------------------
project = "RobStatTM-Py"
author = "Aakarsh Gupta"
copyright = "2026, Aakarsh Gupta"
release = "0.0.1.dev0"

# -- General configuration ---------------------------------------------------
extensions = [
    "myst_parser",        # Markdown support
    "sphinx_design",      # grids, cards, tabs
    "sphinx_copybutton",  # copy button on code blocks
]

# MyST extensions we actually use across the pages.
myst_enable_extensions = [
    "colon_fence",    # ::: fenced directives (used on the landing page only)
    "deflist",
    "fieldlist",
    "attrs_inline",
]
myst_heading_anchors = 3   # auto-generate anchors for h1-h3 (cross-page links)

source_suffix = {".md": "markdown"}
master_doc = "index"

# Files/folders Sphinx should not try to build as pages.
exclude_patterns = [
    "_build",
    "_rd_json",
    "examples",
    "scripts",
    "templates",
    "misc",
    # Contributor-facing design docs now live in `dev/design/` (outside the
    # docs tree), so they are no longer listed here. The two maintainer files
    # that remain in `docs/` are kept out of the built site:
    "RELEASING.md",
    "README.md",
]

# -- HTML output -------------------------------------------------------------
html_theme = "furo"
html_title = "RobStatTM-Py"
# Static assets (pre-rendered plot gallery images live in _static/plots/;
# regenerate with `python docs/scripts/render_plots.py`, needs R + [plots]).
html_static_path = ["_static"]
html_theme_options = {
    "source_repository": "https://github.com/Aakarsh751/robstattm-py",
    "source_branch": "main",
    "source_directory": "docs/",
    "navigation_with_keys": True,
}
# Pygments styles for light/dark code blocks.
pygments_style = "friendly"
pygments_dark_style = "monokai"
